# Generated by Django 3.2.9 on 2021-11-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20211108_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书列表', 'verbose_name_plural': '图书列表'},
        ),
    ]
